apiVersion: v1
kind: Pod
metadata:
  name: experimental-builder
spec:
  serviceAccountName: experimental-builder
  containers:
  - name: experimental-builder
    image: busybox
    command:
    - "/bin/sh"
    - "-c"
    - "for i in `seq 1 500`; do echo Hello && sleep 2; done"
