apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: builder-b
spec:
  failedBuildsHistoryLimit: 5
  output:
    to:
      kind: ImageStreamTag
      name: bin-b:latest
  source:
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: DockerImage
        name: 172.30.1.1:5000/test/bin-a:latest
    type: Source